package com.summit.harnessexample.service;

import com.summit.core.tool.ChoiceDecideGate;
import com.summit.core.tool.DecideRegistry;
import com.summit.harnessexample.common.ApiException;
import com.summit.harnessexample.common.ResultCode;
import com.summit.runtime.toolSupport.DefaultChoiceDecideRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Decision rules of {@link ChoiceDecideService}: the options generated by the model are a
 * recommendation, not a whitelist — picking one and answering with custom free-form text are
 * both accepted, while blank / oversized answers and stale (unknown or already decided) tool
 * calls are rejected.
 */
class ChoiceDecideServiceTest {

    private static final String TOOL_EXECUTION_ID = "tool-exec-1";
    private static final List<String> OPTIONS = List.of("Maven", "Gradle");

    private DecideRegistry<ChoiceDecideGate, String> registry;
    private ChoiceDecideService service;

    @BeforeEach
    void setUp() {
        registry = new DefaultChoiceDecideRegistry();
        service = new ChoiceDecideService(registry);
    }

    private ChoiceDecideGate pendingChoice(List<String> choices) {
        ChoiceDecideGate gate = new ChoiceDecideGate(TOOL_EXECUTION_ID,
                new ChoiceDecideGate.Choice("这个模块用哪种构建方式？", choices));
        registry.register(TOOL_EXECUTION_ID, gate);
        return gate;
    }

    @Test
    void acceptsOneOfTheOptionsOfferedByTheModel() {
        pendingChoice(OPTIONS);

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "Gradle");

        assertThat(data)
                .containsEntry("choice", "Gradle")
                .containsEntry("offeredOption", true)
                .containsEntry("custom", false);
        assertThat(registry.get(TOOL_EXECUTION_ID).getDecision()).isEqualTo("Gradle");
    }

    @Test
    void acceptsACustomAnswerOutsideTheOfferedOptions() {
        pendingChoice(OPTIONS);

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "用 Bazel，并加上 CI 缓存");

        assertThat(data)
                .containsEntry("choice", "用 Bazel，并加上 CI 缓存")
                .containsEntry("offeredOption", false)
                .containsEntry("custom", true);
        assertThat(registry.get(TOOL_EXECUTION_ID).getDecision()).isEqualTo("用 Bazel，并加上 CI 缓存");
    }

    @Test
    void acceptsAnyAnswerWhenTheModelOfferedNoOptions() {
        pendingChoice(List.of());

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "你看着办，先给我方案");

        assertThat(data)
                .containsEntry("offeredOption", false)
                .containsEntry("custom", true);
        assertThat(registry.get(TOOL_EXECUTION_ID).getDecision()).isEqualTo("你看着办，先给我方案");
    }

    @Test
    void trimsTheAnswerAndStillMatchesTheOfferedOptions() {
        pendingChoice(OPTIONS);

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "  Gradle  ");

        assertThat(data)
                .containsEntry("choice", "Gradle")
                .containsEntry("offeredOption", true);
    }

    @Test
    void rejectsABlankAnswer() {
        pendingChoice(OPTIONS);

        assertThatThrownBy(() -> service.decide(TOOL_EXECUTION_ID, "   "))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.BAD_REQUEST.code())
                .hasMessageContaining("must not be blank");
        assertThat(registry.get(TOOL_EXECUTION_ID).isPending()).isTrue();
    }

    @Test
    void rejectsAnAnswerThatIsTooLong() {
        pendingChoice(OPTIONS);
        String tooLong = "x".repeat(ChoiceDecideService.MAX_ANSWER_LENGTH + 1);

        assertThatThrownBy(() -> service.decide(TOOL_EXECUTION_ID, tooLong))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.BAD_REQUEST.code())
                .hasMessageContaining("must not exceed " + ChoiceDecideService.MAX_ANSWER_LENGTH);
        assertThat(registry.get(TOOL_EXECUTION_ID).isPending()).isTrue();
    }

    @Test
    void rejectsAnUnknownToolExecutionId() {
        assertThatThrownBy(() -> service.decide("unknown", "Gradle"))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.NOT_FOUND.code());
    }

    @Test
    void rejectsAnAlreadyDecidedChoice() {
        pendingChoice(OPTIONS);
        service.decide(TOOL_EXECUTION_ID, "Maven");

        assertThatThrownBy(() -> service.decide(TOOL_EXECUTION_ID, "Gradle"))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.CONFLICT.code());
        assertThat(registry.get(TOOL_EXECUTION_ID).getDecision()).isEqualTo("Maven");
    }
}
