package com.summit.harnessexample.service;

import com.summit.core.runtime.LoopSuspender;
import com.summit.core.runtime.SuspensionDecision;
import com.summit.core.runtime.SuspensionRequest;
import com.summit.harnessexample.common.ApiException;
import com.summit.harnessexample.common.ResultCode;
import com.summit.runtime.suspension.InMemoryLoopSuspender;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.function.BooleanSupplier;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.catchThrowableOfType;

/**
 * Decision rules of {@link ChoiceDecideService} on the framework's generic suspension SPI: the
 * options generated by the model are a recommendation, not a whitelist — picking one and answering
 * with custom free-form text are both accepted, while blank / oversized answers and stale (unknown
 * or already decided) tool calls are rejected.
 */
class ChoiceDecideServiceTest {

    private static final String TOOL_EXECUTION_ID = "tool-exec-1";
    private static final List<String> OPTIONS = List.of("Maven", "Gradle");

    private final LoopSuspender suspender = new InMemoryLoopSuspender();
    private final CompletableFuture<SuspensionDecision> resumption = new CompletableFuture<>();
    private ChoiceDecideService service;

    @BeforeEach
    void setUp() {
        service = new ChoiceDecideService(suspender);
    }

    /** Blocks a virtual thread inside {@link LoopSuspender#suspend} so a decision has something to resume. */
    private void pendingChoice(List<String> choices) {
        SuspensionRequest request = new SuspensionRequest(TOOL_EXECUTION_ID, "turn-1", "session-1", "choice",
                Map.of("question", "这个模块用哪种构建方式？", "choices", choices), Duration.ofMinutes(1));
        Thread.ofVirtual().start(() -> resumption.complete(suspender.suspend(request)));
        awaitUntil(() -> suspender.find(TOOL_EXECUTION_ID).isPresent());
    }

    private static void awaitUntil(BooleanSupplier condition) {
        long deadline = System.currentTimeMillis() + 5_000;
        while (!condition.getAsBoolean()) {
            if (System.currentTimeMillis() > deadline) {
                throw new IllegalStateException("the suspension was never registered");
            }
            try {
                Thread.sleep(10);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new IllegalStateException(e);
            }
        }
    }

    private Map<String, Object> resumedPayload() throws Exception {
        return resumption.get(5, TimeUnit.SECONDS).payload();
    }

    @Test
    void acceptsOneOfTheOptionsOfferedByTheModel() throws Exception {
        pendingChoice(OPTIONS);

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "Gradle");

        assertThat(data)
                .containsEntry("question", "这个模块用哪种构建方式？")
                .containsEntry("choice", "Gradle")
                .containsEntry("offeredOption", true)
                .containsEntry("custom", false);
        assertThat(resumedPayload()).containsEntry("answer", "Gradle");
    }

    @Test
    void acceptsACustomAnswerOutsideTheOfferedOptions() throws Exception {
        pendingChoice(OPTIONS);

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "用 Bazel，并加上 CI 缓存");

        assertThat(data)
                .containsEntry("choice", "用 Bazel，并加上 CI 缓存")
                .containsEntry("offeredOption", false)
                .containsEntry("custom", true);
        assertThat(resumedPayload()).containsEntry("answer", "用 Bazel，并加上 CI 缓存");
    }

    @Test
    void acceptsAnyAnswerWhenTheModelOfferedNoOptions() throws Exception {
        pendingChoice(List.of());

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "你看着办，先给我方案");

        assertThat(data)
                .containsEntry("offeredOption", false)
                .containsEntry("custom", true);
        assertThat(resumedPayload()).containsEntry("answer", "你看着办，先给我方案");
    }

    @Test
    void trimsTheAnswerAndStillMatchesTheOfferedOptions() {
        pendingChoice(OPTIONS);

        Map<String, Object> data = service.decide(TOOL_EXECUTION_ID, "  Gradle  ");

        assertThat(data)
                .containsEntry("choice", "Gradle")
                .containsEntry("offeredOption", true);
    }

    @Test
    void rejectsABlankAnswerAndLeavesTheSuspensionPending() {
        pendingChoice(OPTIONS);

        assertThatThrownBy(() -> service.decide(TOOL_EXECUTION_ID, "   "))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.BAD_REQUEST.code())
                .hasMessageContaining("must not be blank");
        assertThat(resumption).isNotDone();
    }

    @Test
    void rejectsAnAnswerThatIsTooLong() {
        pendingChoice(OPTIONS);
        String tooLong = "x".repeat(ChoiceDecideService.MAX_ANSWER_LENGTH + 1);

        assertThatThrownBy(() -> service.decide(TOOL_EXECUTION_ID, tooLong))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.BAD_REQUEST.code())
                .hasMessageContaining("must not exceed " + ChoiceDecideService.MAX_ANSWER_LENGTH);
        assertThat(resumption).isNotDone();
    }

    @Test
    void rejectsAnUnknownToolExecutionId() {
        assertThatThrownBy(() -> service.decide("unknown", "Gradle"))
                .isInstanceOf(ApiException.class)
                .hasFieldOrPropertyWithValue("code", ResultCode.NOT_FOUND.code());
    }

    @Test
    void rejectsASecondDecisionOnTheSameToolCall() throws Exception {
        pendingChoice(OPTIONS);
        service.decide(TOOL_EXECUTION_ID, "Maven");
        assertThat(resumedPayload()).containsEntry("answer", "Maven");

        // The in-memory suspender drops the entry as soon as the blocked loop resumes, so a stale
        // card is either reported as an unknown suspension or as an already-decided one.
        ApiException error = catchThrowableOfType(
                () -> service.decide(TOOL_EXECUTION_ID, "Gradle"), ApiException.class);

        assertThat(error).isNotNull();
        assertThat(error.getCode()).isIn(ResultCode.CONFLICT.code(), ResultCode.NOT_FOUND.code());
    }
}
